# Generated by Django 4.1.9 on 2023-06-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0006_delete_apple_delete_google_delete_meta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apple',
            fields=[
                ('_id', models.IntegerField(max_length=500, primary_key=True, serialize=False)),
                ('query', models.CharField(default='Apple', editable=False, max_length=10)),
                ('batch', models.CharField(max_length=500)),
                ('title', models.TextField(max_length=1000)),
                ('link', models.TextField(max_length=2000)),
                ('ago', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Google',
            fields=[
                ('_id', models.IntegerField(max_length=500, primary_key=True, serialize=False)),
                ('query', models.CharField(default='Google', editable=False, max_length=10)),
                ('batch', models.CharField(max_length=500)),
                ('title', models.TextField(max_length=1000)),
                ('link', models.TextField(max_length=2000)),
                ('ago', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('_id', models.IntegerField(max_length=500, primary_key=True, serialize=False)),
                ('query', models.CharField(default='Meta', editable=False, max_length=10)),
                ('batch', models.CharField(max_length=500)),
                ('title', models.TextField(max_length=1000)),
                ('link', models.TextField(max_length=2000)),
                ('ago', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Microsoft',
            fields=[
                ('_id', models.IntegerField(max_length=500, primary_key=True, serialize=False)),
                ('query', models.CharField(default='Microsoft', editable=False, max_length=10)),
                ('batch', models.CharField(max_length=500)),
                ('title', models.TextField(max_length=1000)),
                ('link', models.TextField(max_length=2000)),
                ('ago', models.DateField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
