# Generated by Django 4.1.9 on 2023-06-07 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_apple__id_alter_google__id_alter_meta__id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apple',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.DeleteModel(
            name='Microsoft',
        ),
    ]
